# Generated by Django 5.2 on 2025-04-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('date', models.DateField(verbose_name='撮影日')),
                ('time', models.TimeField(verbose_name='時間帯')),
                ('plan', models.CharField(blank=True, max_length=100, null=True, verbose_name='プラン')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='撮影場所')),
            ],
        ),
    ]
