# Generated by Django 5.2 on 2025-04-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_booking_app', '0002_reservation_delete_photosession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
            ],
            options={
                'unique_together': {('date', 'start_time')},
            },
        ),
    ]
