# Generated by Django 5.2 on 2025-04-24 04:44

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from datetime import time


class Migration(migrations.Migration):

    dependencies = [
        ('photo_booking_app', '0004_alter_reservation_unique_together_reservation_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'start_time')},
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='ay.1031.ld@gmail.com', max_length=254, verbose_name='メールアドレス'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='children_name',
            field=models.CharField(max_length=100, verbose_name='お子様のお名前'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='予約日'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=time(12, 0)),  # 12:00 の時間をデフォルト値として設定
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(blank=True, verbose_name='ご不明点やご要望などお気軽にお書きください'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='plan',
            field=models.CharField(choices=[('basic', 'ベーシックプラン'), ('753', '七五三プラン')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),  # デフォルト値の削除
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]