# Generated by Django 5.2 on 2025-04-24 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_booking_app', '0005_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
